// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDI-VpqpiaKBqKHHr8hYUBXgk7y9R2DF5s',
    appId: '1:363051354125:web:e12348b65bd97aead4ad44',
    messagingSenderId: '363051354125',
    projectId: 'mrclean-843dd',
    authDomain: 'mrclean-843dd.firebaseapp.com',
    storageBucket: 'mrclean-843dd.appspot.com',
    measurementId: 'G-KP5NH96SFC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYjR4EHm2c4BSVAHEbeMUlk8VEwmmRAWk',
    appId: '1:363051354125:android:e6ecb29a153e7dd4d4ad44',
    messagingSenderId: '363051354125',
    projectId: 'mrclean-843dd',
    storageBucket: 'mrclean-843dd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDb6anDRgkGj5QB79T-nWDcrmQL9tUmdV0',
    appId: '1:363051354125:ios:19a46a1bac41d9b3d4ad44',
    messagingSenderId: '363051354125',
    projectId: 'mrclean-843dd',
    storageBucket: 'mrclean-843dd.appspot.com',
    iosBundleId: 'com.example.mrclean',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDb6anDRgkGj5QB79T-nWDcrmQL9tUmdV0',
    appId: '1:363051354125:ios:c74ce038e2b31845d4ad44',
    messagingSenderId: '363051354125',
    projectId: 'mrclean-843dd',
    storageBucket: 'mrclean-843dd.appspot.com',
    iosBundleId: 'com.example.mrclean.RunnerTests',
  );
}
